version: '3.1'
services:
  {{ cookiecutter.project_slug }}:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: {{ cookiecutter.project_slug }}
    command: adev runserver main.py --host=0.0.0.0 --port={{cookiecutter.port}}
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "{{ cookiecutter.port }}:{{ cookiecutter.port }}"
